server:
  port: 7002
  ssl:
    enabled: false
  compression:
    enabled: true

account:
  storage:
    enabled: true

credentials:
  poller:
    enabled: false
    types:
      kubernetes:
        reloadFrequencyMs: 60000

sql:
  enabled: true
  # read-only boolean toggles `SELECT` or `DELETE` health checks for all pools.
  # Especially relevant for clouddriver-ro and clouddriver-ro-deck which can
  # target a SQL read replica in their default pools.
  read-only: false
  taskRepository:
    enabled: true
  cache:
    enabled: false
  scheduler:
    enabled: false
  # Enable clouddriver-caching's clean up agent to periodically purge old
  # clusters and accounts. Set to true when using the Kubernetes provider.
  unknown-agent-cleanup-agent:
    enabled: false
  connectionPools:
    default:
      # additional connection pool parameters are available here,
      # for more detail and to view defaults, see:
      # https://github.com/spinnaker/kork/blob/master/kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/ConnectionPoolProperties.kt
      default: true
      #jdbcUrl: jdbc:mysql://mysql:3306/clouddriver?useSSL=false&useUnicode=true&characterEncoding=utf8
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/clouddriver?useSSL=false&useUnicode=true&characterEncoding=utf8
      user: root #clouddriver #root
      password: root #clouddriver #root
      # password: depending on db auth and how spinnaker secrets are managed

  migration:
    user: root #clouddriver #root
    password: root #clouddriver #root
    #jdbcUrl: jdbc:mysql://mysql:3306/clouddriver?useSSL=false&useUnicode=true&characterEncoding=utf8
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/clouddriver?useSSL=false&useUnicode=true&characterEncoding=utf8

redis:
  enabled: false
  cache:
    enabled: false
  scheduler:
    enabled: false
  taskRepository:
    enabled: false
  #connection: ${services.redis.baseUrl:redis://redis:6379}
  connection: ${services.redis.baseUrl:redis://localhost:6379}
  parallelism: -1

dualTaskRepository:
  enabled: false
  primaryClass: com.netflix.spinnaker.clouddriver.sql.SqlTaskRepository
  previousClass: com.netflix.spinnaker.clouddriver.data.task.jedis.RedisTaskRepository

services:
  front50:
    baseUrl: http://localhost:8080
  fiat:
    enabled: false
    baseUrl: http://localhost:7003

management.health.elasticsearch.enabled: false

swagger:
  enabled: true
  title: clouddriver
  description: Cloud read and write operations
  contact: admin@host.net
  patterns:
    - .*elasticIps.*
    - .*cache.*
    - .*instance.*
    - .*search.*
    - .*security.*
    - .*vpcs.*
    - .*credentials.*
    - .*networks.*
    - .*subnets.*
    - .*ops.*
    - .*task.*
    - .*applications.*
    - .*aws.*
    - .*azure.*
    - .*appengine.*
    - .*gce.*
    - .*kubernetes.*
    - .*instances.*
    - .*reports.*
    - .*docker.*
    - .*job.*
    - .*process.*
    - .*dcos.*
    - .*tasks.*
    - .*auth.*
    - .*applications.*
    - .*securityGroups.*
    - /search
    - .*pipeline.*
    - .*pipelineConfigs.*
    - .*pipelines.*
    - .*loadBalancers.*
    - .*instances.*
    - .*images.*
    - .*credentials.*
    - .*events.*
    - .*builds.*
    - .*instanceTypes.*
    - .*bakery.*
    - .*executions.*
    - .*webhooks.*
    - .*firewalls.*
    - .*version.*
    - .*pubsub.*
    - .*projects.*
    - .*functions.*
    - .*managed.*
    - .*plugins.*
    - /default/.*
    - /credentials.*
    - /global/.*
    - /notifications.*
    - /pipelines.*
    - /strategies.*
    - /v2/.*

default:
  # legacyServerPort is a non-ssl listener, if ssl is enabled. -1 to disable
  legacyServerPort: -1
  account:
    env: default

aws:
  enabled: false
#  features:
#    launch-templates:
#      enabled: true
#      allowed-applications: app1:account1:region1,app2:account1:region1
#      all-applications: false
#      allowed-accounts-regions: account1:region1
#      allowed-accounts: account1,account2
#      excluded-applications: ""
#      excluded-accounts: account3,account4
  # proxy:
  #  proxyHost: 10.0.0.54
  #  proxyPort: 8888
  #  proxyUsername: foo
  #  proxyPassword: foo
  #  proxyDomain: foo
  #  proxyWorkstation: foo
  #  protocol: HTTP
  defaults:
    iamRole: BaseIAMRole
    unknownInstanceTypeBlockDevice:
      deviceName: /dev/sdb
      size: 40
    instanceClassBlockDevices:
    - instanceClass: m3
      blockDevices:
      - deviceName: /dev/sdb
        virtualName: ephemeral0
      - deviceName: /dev/sdc
        virtualName: ephemeral1
  defaultRegions:
    - name: us-east-1
  defaultKeyPairTemplate: '{{name}}-keypair'

  # an empty list means we are directly managing the AWS account we have credentials for (named default.account.env)
  # see prod profile section below for an example configuration to manage other accounts via STS assume role
  accounts: []

azure:
  enabled: false
  defaults:

  accounts:
    - name: my-azure-account
      clientId: ${AZURE_CLIENT_ID}
      appKey: ${AZURE_APPKEY}
      tenantId: ${AZURE_TENANT_ID}
      subscriptionId: ${AZURE_SUBSCRIPTION_ID}
      regions: ["westus", "eastus", "eastus2", "centralus"]
      defaultResourceGroup: ${AZURE_DEFAULT_RESOURCE_GROUP:"SpinnakerDefault"}
      defaultKeyVault: ${AZURE_DEFAULT_KEYVAULT}
      vmImages:
      - publisher: "MicrosoftWindowsServer"
        offer: "WindowsServer"
        sku: "2012-R2-Datacenter"
        version: "4.0.20151214"
      - publisher: "Canonical"
        offer: "UbuntuServer"
        sku: "14.04.5-LTS"
        version: "14.04.201612130"
      - publisher: "credativ"
        offer: "Debian"
        sku: "8"
        version: "8.0.201602010"
      - publisher: "OpenLogic"
        offer: "CentOS"
        sku: "7.1"
        version: "7.1.20150731"
      - publisher: "SUSE"
        offer: "openSUSE-Leap"
        sku: "42.1"
        version: "2016.01.14"
      - publisher: "SUSE"
        offer: "SLES"
        sku: "12-SP1"
        version: "2015.12.15"
  # Example how to set the Azure storage connection string related entries for retrieving the list of available custom VM images,
  #  where "scs" represents the Azure Storage connection string and "blobDir" is the relative path to the custom images container
  #
  #    customImages:
  #    - scs: ${AZURE_SCS1}
  #      blobDir: "system/Microsoft.Compute/Images/vhds"
  #      osType: "Windows"
  #      region: "westus"
  #    - scs: ${AZURE_SCS2}
  #      blobDir: "vhds"
  #      osType: "Linux"
  #      region: "westus"

appengine:
  enabled: false

cloudrun:
  enabled: false

google:
  enabled: false
  baseImageProjects:
  - centos-cloud
  - coreos-cloud
  - cos-cloud
  - debian-cloud
  - opensuse-cloud
  - rhel-cloud
  - suse-cloud
  - ubuntu-os-cloud
  - windows-cloud
  accounts:
    - name: my-gcp-account
      project: my-gcp-project
      required: true # Forces the account to be valid at startup
      alphaListed: true # Project is enabled for alpha features at GCP
      jsonPath: /root/.gcp/my-gcp-project.json
      imageProjects: # Additional projects that can images for deploying
        - my-gcp-image-project
  defaults:
    fallbackInstanceTypeDisks:
    - type: pd-ssd
      sizeGb: 10
    instanceTypeDisks:
    - instanceType: n1-standard-1
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: n1-standard-2
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: n1-standard-4
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: n1-standard-8
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: n1-standard-16
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: n1-standard-32
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: f1-micro
      supportsLocalSSD: false
      disks:
      - type: pd-standard
        sizeGb: 10
    - instanceType: g1-small
      supportsLocalSSD: false
      disks:
      - type: pd-standard
        sizeGb: 10
    - instanceType: n1-highmem-2
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: n1-highmem-4
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: n1-highmem-8
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: n1-highmem-16
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: n1-highmem-32
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: n1-highcpu-2
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: n1-highcpu-4
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: n1-highcpu-8
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: n1-highcpu-16
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: n1-highcpu-32
      disks:
      - type: pd-ssd
        sizeGb: 10
    - instanceType: default
      disks:
      - type: pd-ssd
        sizeGb: 10

kubernetes:
  enabled: true
  v2:
    applyAppLabels: true

dockerRegistry:
  enabled: false

dcos:
  enabled: false

cf:
  enabled: false
  accounts:
    - name: ${providers.cf.primaryCredentials.name}
      api: ${providers.cf.primaryCredentials.api}
      console: ${providers.cf.primaryCredentials.console}
      org: ${providers.cf.defaultOrg}
      space: ${providers.cf.defaultSpace}
      username: ${cf.account.name}
      password: ${cf.account.password}
      artifactUsername: ${cf.repo.username}
      artifactPassword: ${cf.repo.password}

oracle:
  enabled: false

spring:
  jackson:
    mapper:
      SORT_PROPERTIES_ALPHABETICALLY: true
    serialization:
      ORDER_MAP_ENTRIES_BY_KEYS: true

operations.security:
  onMissingSecuredCheck: WARN
  onMissingValidator: WARN

# Turn on when confirming Fiat authorization checks
# logging.level.com.netflix.spinnaker.clouddriver.listeners: DEBUG

resilience4j.retry:
  instances:
    sqlTransaction:
      maxRetryAttempts: 5
      waitDuration: 100ms
      enableExponentialBackoff: false
      ignoreExceptions:
      - com.netflix.spinnaker.clouddriver.event.exceptions.AggregateChangeRejectedException
    sqlRead:
      maxRetryAttempts: 5
      waitDuration: 100ms
      enableExponentialBackoff: false

---

spring:
  profiles: prod

# example https configuration for client auth to services:
#default:
  # legacyServerPort is a non-ssl listener when the main listener has SSL enabled
  #legacyServerPort: 8501

#server:
  #ssl:
    # enabled: true
    # keyStore: clouddriver-keystore.p12
    # keyStoreType: PKCS12
    # keyStorePassword: changeme
    # trustStore: services-truststore.p12
    # trustStoreType: PKCS12
    # trustStorePassword: changeme
    # clientAuth: need

#aws:
  # example configuration for managing multiple accounts
  # role in managed account to assume:
  #defaultAssumeRole: role/myrole
  #accounts:
    # - name: account-display-name
    #   defaultKeyPair: key-pair
    #   edda: http://edda.{{region}}.host.net:7001
    #   discovery: "http://{{region}}.discovery.host.net:7001/eureka"
    #   accountId: 123456789012
    #   regions: #override default regions
    #     - name: us-east-1
    #     - name: ap-northeast-1
    #   externalId: a1b2c3d4

---

# local profile is activated by default when running the application - override values here for local development
#  for production, set spring.profiles.active to select the appropriate profile for your environment
spring:
  profiles: local

aws:
  enabled: false

# an AWSCredentialsProvider that obtains session credentials via SSH through a bastion instance (useful for local development):
#bastion:
#  enabled: false
#  port: 22
#  proxyRegion: us-west-1
#  proxyCluster: my-credentials-cluster

---
# This profile is used in HA deployments for a clouddriver that handles read-only requests from
# other services
spring:
  profiles: ro

redis:
  connection: ${services.redisRo.baseUrl:${services.redis.baseUrl}}

caching:
  writeEnabled: false

aws:
  enabled: false

---
# This profile is used in HA deployments for a clouddriver that handles mutating requests from
# other services, but does not run caching agents
spring:
  profiles: rw

caching:
  writeEnabled: false

aws:
  enabled: false
